# Use the official Node.js image as the base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install the application dependencies
RUN npm ci --only=production

# Copy the application files into the working directory
COPY . .

# Expose port (if needed)
EXPOSE 3000

# Define the entry point for the container
CMD ["npm", "start"]